import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import FooterNav from './component/ui/footer-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ja'>
			<body className={inter.className}>
				<main className='pb-16'>
					{children}
					<FooterNav />
				</main>
			</body>
		</html>
	);
}
